<?php
/**
 * Contao Open Source CMS
 *
 * Copyright (c) 2017 Heimrich & Hannot GmbH
 *
 * @author  Thomas Körner <t.koerner@heimrich-hannot.de>
 * @license http://www.gnu.org/licences/lgpl-3.0.html LGPL
 */


namespace HeimrichHannot\Share\PdfModule;


use HeimrichHannot\Share\PdfModule;

class MpdfModule extends PdfModule
{
    /**
     * @var \mPDF
     */
    protected $pdf;
    protected $inline = true;
    protected $filename;
    protected $content;

    public function __construct()
    {
        $this->pdf = new \mPDF();
    }

    public function setInline($inline)
    {
        if (is_bool($inline))
        {
            $this->inline = $inline;
        }
        return $this->inline;
    }

    public function setFileName($name)
    {
        if (!empty($name))
        {
            return $this->filename = $name;
        }
        return $this->filename;
    }

    /**
     * Add Html content to render
     *
     * @param $content string
     *
     * @return mixed true if added successfully, null if not supported
     */
    public function addHtmlContent($content)
    {
        $this->pdf->WriteHTML($content, 0);
    }

    public function setFontSize($size)
    {
        return parent::setFontSize($size); // TODO: Change the autogenerated stub
    }


    public function compile()
    {
        $pdf = $this->pdf;
        $outputInline = $this->() ? "I" : "D";
        $content = '';
        if (!empty($this->content)) {
            foreach ($this->content as $item) {
                $content .= $item;
            }
        }
        $pdf->Output($this->filename.'.pdf', $outputInline);
    }
}